"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "kasya a.r."
email = "kasyaar@gmail.com"

[aliases]
s = ["status", "--no-pager"]
fl = ["log", "-r", "~root()"]
d = ["describe"]
l = ["log", "--limit", "5", "--no-pager", "-r", "~root()"]

[ui]
default-command = "s"
editor = "vim"
